# Generated by Django 3.0.5 on 2020-04-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='slug',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
    ]
