# Generated by Django 3.0.5 on 2020-04-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200402_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='place',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
